library('fdaPDE')
rm(list=ls())
load("uniformmesh.RData")

mesh <- create.mesh.2D(nodes=t$pts, segments=cbind(t$bnd.ind, c(t$bnd.ind[-1], 1)))
mesh2 <- refine.by.splitting.mesh.2D(mesh)
mesh3 <- refine.mesh.2D(mesh, maximum_area = 0.025, minimum_angle = 30)

pdf(file = "meshes.pdf") #, width = 1200, height = 1200, res = 300)
layout(matrix(c(1,3,2,2), 2, 2, byrow=T))
plot(mesh)
title(paste("Uniform, with", nrow(mesh$nodes)), "nodes")
plot(mesh2)
title(paste("Uniform, with", nrow(mesh2$nodes)), "nodes")
plot(mesh3)
title(paste("Uniform, with", nrow(mesh3$nodes)), "nodes")
dev.off()
